# Generated by Django 1.10.7 on 2017-07-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0021_user_resume_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referer",
            field=models.TextField(blank=True, null=True),
        ),
    ]
