# Generated by Django 5.2.17 on 2026-08-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0072_remove_facebook_github_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
