# Generated by Django 5.2.17 on 2026-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0074_set_site_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(blank=True, default="", max_length=255),
        ),
    ]
