# Generated by Django 5.2.17 on 2026-08-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0075_add_user_pending_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobalert",
            name="name",
            field=models.CharField(max_length=2000),
        ),
    ]
