# Generated by Django 5.2.17 on 2026-08-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0076_jobalert_name_not_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="internship_content",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="city",
            name="internship_meta_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="city",
            name="internship_meta_title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="city",
            name="internship_text",
            field=models.CharField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="city",
            name="meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="meta_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="city",
            name="meta_title",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="city",
            name="page_content",
            field=models.TextField(blank=True, default=""),
        ),
    ]
