# Generated by Django 5.2.17 on 2026-08-13 15:40

"""Drop the "Careers" registration source.

Choices-only AlterField: Postgres does not enforce `choices`, so this touches no
rows and is reversible. Its only writer was the `/process-email/` webhook,
deleted with `pjob/`; no user in the production snapshot was created that way.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0077_city_optional_seo_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="registered_from",
            field=models.CharField(
                choices=[
                    ("Email", "Email"),
                    ("Social", "Social"),
                    ("ResumePool", "ResumePool"),
                    ("Resume", "Resume"),
                ],
                default="",
                max_length=15,
            ),
        ),
    ]
