# Generated by Django 5.2.17 on 2026-08-13 16:02

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peeldb", "0079_pg_trgm_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="search_vector",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.contrib.postgres.search.CombinedSearchVector(
                    django.contrib.postgres.search.CombinedSearchVector(
                        django.contrib.postgres.search.CombinedSearchVector(
                            django.contrib.postgres.search.SearchVector(
                                "title", config="english", weight="A"
                            ),
                            "||",
                            django.contrib.postgres.search.SearchVector(
                                "job_role", config="english", weight="B"
                            ),
                            django.contrib.postgres.search.SearchConfig("english"),
                        ),
                        "||",
                        django.contrib.postgres.search.SearchVector(
                            "company_name", config="english", weight="C"
                        ),
                        django.contrib.postgres.search.SearchConfig("english"),
                    ),
                    "||",
                    django.contrib.postgres.search.SearchVector(
                        "description", config="english", weight="D"
                    ),
                    django.contrib.postgres.search.SearchConfig("english"),
                ),
                output_field=django.contrib.postgres.search.SearchVectorField(),
            ),
        ),
        migrations.AddIndex(
            model_name="jobpost",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="jobpost_search_vector_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="jobpost",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="jobpost_title_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
